version: '3.9'
services:  
  db_app:
    image: mysql:8.0.29
    container_name: db_app
    command: --default-authentication-plugin=mysql_native_password
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_app
      MYSQL_USER: db_app
      MYSQL_PASSWORD: db_app
    volumes:
      - "./migrations/create-company.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - 8002:3306
    networks:
      - api_net

  api_myadmin:
    image: phpmyadmin:latest
    container_name: api_myadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - api_net

networks:
  api_net:
    driver: bridge